"""Pydantic models for music generation."""

from pathlib import Path

from pydantic import BaseModel


class GeneratedSong(BaseModel):
    """Represents a song generated by Suno or mock."""

    suno_id: str = ""
    audio_url: str = ""
    local_path: Path | None = None
    prompt: str = ""
    style: str = ""
    duration_sec: float = 0.0
